### ISSUE TITLE
Collate data from parallel runs

### ISSUE THREAD

**Issue by goromlagche** [toptal/crystalball#132]
When running crystalball in a parallel test setup, we will have multiple `crystalball_data.yml` files generated.
Currently we need to write a script to merge all the different `crystalball_data_*.yml` files from the different runs into one single file. 

It will be really helpful if the library itself supports that. For example something like [SimpleCov.collate](https://github.com/simplecov-ruby/simplecov#merging-test-runs-under-different-execution-environments)

**Comment by pluff** [comment]
@goromlagche you don't have to merge them together. If you set a directory in [execution_map_path](https://github.com/toptal/crystalball/blob/master/spec/fixtures/crystalball.yml#L2) Crystalball will read all the files from that directory.

**Comment by goromlagche** [comment]
@pluff Thank you so much. that helps a lots :clap: :+1:
